server:
  port: 8081

file:
  storage:
    location: fileStorage

spring:
  servlet:
    multipart:
      enabled: true
      location: temp123
      file-size-threshold: 5MB
      max-file-size: 1MB
      max-request-size: 20MB

  datasource:
    url: jdbc:mysql://localhost:3306/fileupload?useSSL=false
    username: hitsa
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


